### ISSUE TITLE
V11

### ISSUE THREAD

**Issue by Lina28011** [mclemente/simplefog#10]
Plz add v11 support

**Comment by mclemente** [comment]
You should be able to install the V11 version through FoundryVTT's Install Module window already, just like every other module.

Your issue made me notice that the latest V11 version (1.1.1) wasn't listed yet, though, only the initial 1.0 version. I've since fixed that.

**Comment by mclemente** [comment]
Btw, if you're trying to update and getting the "Release is for V12" warning, just reinstall the module and it should install the last V11-compatible release.
