### ISSUE TITLE
v12

### ISSUE THREAD

**Issue by brunocalado** [mclemente/simplefog#11]
Hi!

Can you update this module to v12?

Thank you.

**Comment by mclemente** [comment]
It already supports V12 since 3 weeks ago (1.2.0).

If you're here because of the "new" release on the Foundry discord, I was just updating the latest V11 release, since the V11 release listed there was 1.0.

**Comment by brunocalado** [comment]
> It already supports V12 since 3 weeks ago (1.2.0).
> 
> If you're here because of the "new" release on the Foundry discord, I was just updating the latest V11 release, since the V11 release listed there was 1.0.

Thank you!
