### ISSUE TITLE
[BUG] Z rendering setting ignored

### ISSUE THREAD

**Issue by dirkson** [mclemente/simplefog#2]
**Module Version:** v1.1.1

**Describe the bug**
I'm unable to produce any change in behavior by changing the "Simplefog Z-Index" setting. I've tried 50, 1, 0, -999, and 999. All settings result in tokens and fxweather rendering below both the simplefog color and graphic layers.

**Browser:**
 Firefox and Chromium
**Foundry Version:** 
V11 build 315
**Game System:** 
D&D 5e 2.4.0

**Comment by misthero** [comment]
In my case I discovered you have to reload foundry after saving the settings, the module doesn't trigger the reload like other modules do.
I noticed that players could see doors in unexlored areas. And found that to hide doors and leave those below the fog you need to set the z-index to 1000+ (I used 1200 for safety). Anyway no change is perceived unless the players reloaded the page F5.
