### ISSUE TITLE
[BUG] The Simplefog section in Configure Game Settings has two entries that look to be missing actual names

### ISSUE THREAD

**Issue by steveculshaw** [mclemente/simplefog#3]
**Module Version:** v0.3.4

**Describe the bug**
The Simplefog section in Configure Game Settings has two entries that look to be missing actual names; `simplefog.setting.reset.name` and `simplefog.setting.debug.name`

**To Reproduce**
1. Go to Configure Game Settings
2. Scroll down to 'Simplefog'

**Expected behavior**
Add setting correct names.

**Screenshots**
Missing text in dialog ...
<img width="434" alt="image" src="https://github.com/League-of-Foundry-Developers/simplefog/assets/64320/c151b9e2-2b68-449f-8e5a-8408561144fa">

**Foundry Version:** 
11.305 

**Game System:** 
Savage Worlds Adventure Edition 3.0.6

**Additional context**
None

**Comment by mclemente** [comment]
Version 0.3.4 was maintained by the [League of Foundry Devs](https://github.com/League-of-Foundry-Developers/simplefog/).

This repo's first version was 1.0, which fixed that issue already, so I'm closing this issue.
