### ISSUE TITLE
[BUG] Manifest URL for the v11 compatible version points to the latest release, ergo v12 and won't install in v11 Foundry versions

### ISSUE THREAD

**Issue by crovaxon** [mclemente/simplefog#8]
**Module Version:** v1.0.0 according to package listing

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the Gthub issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Package listing at Foundry for the Simple Fog module has a wrong manifest URL for the version 1.0.0 release:
https://github.com/mclemente/simplefog/releases/latest/download/module.json
Which will of course attempt to download the new 1.2.0 version even when running Foundry v11.

**To Reproduce**
1. Go to module install browser in setup in a Foundry v11 instance
2. Search Simple Fog 
3. Attempt to install
4. Get error because incompatible version 1.2.0 installation is being attempted: `Error: module simplefog version 1.2.0 requires a more modern version of the Foundry Virtual Tabletop software: 12 or newer`

**Expected behavior**
Correct manifest URL being used to install the latest v11 compatible version, which should be Simple Fog v1.1.1:
https://github.com/mclemente/simplefog/releases/download/1.1.1/module.json

**Screenshots**

**Browser:**
 Not important

**Foundry Version:** 
v11.315
**Game System:** 
None
**Additional context**
The package listing also lists Simple Fog v1.0.0 as the only v11 compatible version, while a bugfix release v1.1.1 exists, so should be
added as well.

**Comment by mclemente** [comment]
It should be fixed now. Thank you for reporting it.
