### ISSUE TITLE
Hotkey no longer works - Foundry V12 support?

### ISSUE THREAD

**Issue by ndstumme** [mclemente/simplefog#9]
**Module Version:** v1.3.1.0

After upgrading to V12, the hotkey to disable animations no longer works. I can disable animations entirely from the settings menu, but holding Alt or similar no longer disables the animation. There is no F12 console error.

**Browser:**
Firefox 127.0 / Chrome 126.0.6478.126

**Foundry Version:** 
Version 12 Build 327

**Game System:** 
D&D 5e 3.2.1

**Additional context**
The problem persists if I disable all modules except lib-wrapper and simplefog.

**Comment by mclemente** [comment]
Are you sure this is the right module?

The latest version is 1.2.0, not 1.3.1.0. And there is not hotkey to disable animations, and none of them interact with Alt either.

**Comment by ndstumme** [comment]
Sorry! I must have still had this tab open. You're right, this was for a different module. Keep up the good work.
